name: ‚ùå Bug report
description: Report errors or unexpected behavior
labels: ‚ùå bug
body:
- type: checkboxes
  attributes:
      label: üßê Have you read the FAQ and viewed similar issues?
      description: Please read the <a href="https://telegra.ph/SpotX-FAQ-09-19">FAQ</a>. Also check the open and closed <a href="https://github.com/SpotX-Official/SpotX/issues">issue</a> because your issue may have already been fixed.
      options:
        - label: I have read the FAQ
          required: true
        - label: I have checked older issues, open and closed
          required: true
        - label: I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>
          required: true  
- type: markdown
  attributes:
    value: "###"    
- type: input
  id: lang_spoti
  attributes:
    label: –°ountry of your account
    description: You can view your country on your account page, in paragraph <a href="https://www.spotify.com/account/">Country or region</a>.
    placeholder: "e.g. Ukraine"
  validations:
    required: true 
- type: markdown
  attributes:
    value: "###"     
- type: dropdown
  id: plan
  attributes:
    label: What is your Spotify Plan?
    description: You can view your plan on your account page, under <a href="https://www.spotify.com/account/">Your plan</a>.
    options:
      - Free
      - Premium
  validations:
    required: true
- type: markdown
  attributes:
    value: "###"        
- type: dropdown
  id: spicetify
  attributes:
    label: Do you have Spicetify installed?
    description: <a href="https://spicetify.app/">Spicetify</a> is a command line tool to customize Spotify client.
    options:
      - "Yes"
      - "No"
  validations:
    required: true
- type: markdown
  attributes:
    value: "###"       
- type: textarea
  attributes:
    label: ‚Ñπ Computer information
    description: |
      - Spotify: e.g. <kbd>1.1.90.859.gf1bb1e36</kbd>
        - In the open Spotify client in the upper left corner, click <kbd>‚Ä¢‚Ä¢‚Ä¢</kbd> ‚Üí <kbd>Help</kbd> ‚Üí <kbd>About Spotify</kbd>
      - Windows: e.g. <kbd>Windows 11 21H2 22000.527</kbd> 
        - Press <kbd>Win</kbd> + <kbd>Pause/Break</kbd> to open the page to copy from.
      - PowerShell: e.g. <kbd>5.1.19041.1200</kbd>
        - In the Windows PowerShell console, type the following command <kbd>Get-Host | Select-Object Version</kbd>
    placeholder: |
        - Spotify: 
        - Windows: 
        - PowerShell:  
    value: |
        - Spotify: 
        - Windows: 
        - PowerShell: 
    render: markdown   
  validations:
    required: true    
- type: textarea
  attributes:
    label: üìù Description
    description: List steps to reproduce the error and details on what happens and what you expected to happen.
    value: |
      1.
      2.
      3.
      ...
  validations:
    required: true
- type: textarea
  attributes:
    label: üì∏ Screenshots
    description: Place any screenshots of the issue here if needed
  validations:
    required: false    
    